### PR TITLE
Return types

### PR DESCRIPTION
**Pull request by basz**
note: I remove a test which seemed silly to me, but perhaps I misunderstand.

you test a method via a mock. The return values should match the arguments which seems odd. and will always pass due to the expectations on the mock...

let me know, and i'll return it if incorrect.

ps. could you change (https://github.com/Slamdunk/zend-mail-extensions/blob/master/tests/Transport/SmtpTest.php#L27) to english? My italian is non existant... (issues are off, so I've added it here_

### CODE REVIEW

**Review by Slamdunk — CHANGES_REQUESTED** [review]
> note: I remove a test which seemed silly to me, but perhaps I misunderstand.
> 
> you test a method via a mock. The return values should match the arguments which seems odd. and will always pass due to the expectations on the mock...

`TimeKeeperSmtpProxyTest::testProxyPublicMethodsExceptQuitOne` is a vital test: it proves that `TimeKeeperSmtpProxy` is in fact a proxy and doesn't alter what proxied classes do, except for few extended behaviour: time tracking and `$originalProtocol->setUseCompleteQuit(false);`

So it needs to stay there.

> ps. could you change (https://github.com/Slamdunk/zend-mail-extensions/blob/master/tests/Transport/SmtpTest.php#L27) to english? My italian is non existant... (issues are off, so I've added it here_

Done, sorry


Tests and static analysis shall pass before a review can be done, please fix the errors Travis shows.

**Comment by basz** [comment]
```
Rattletrap:zend-mail-extensions bas$ vendor/bin/phpunit --coverage-clover ./clover.xml
PHPUnit 7.0.2 by Sebastian Bergmann and contributors.

Runtime:       PHP 7.1.14 with Xdebug 2.5.5
Configuration: /Users/bas/Sandbox/zend-mail-extensions/phpunit.xml

.......                                                             7 / 7 (100%)

Time: 1.43 seconds, Memory: 8.00MB

OK (7 tests, 106 assertions)

Generating code coverage report in Clover XML format ... done
```
? not understanding

**Comment by Slamdunk** [comment]
At the end of this page you can see the checks that the project decided shall pass for a PR to be condirered valid.
At the time of writing, Travis reports a failing build: https://travis-ci.org/Slamdunk/zend-mail-extensions/builds/354299090

**Comment by basz** [comment]
think its done

**Review by Slamdunk — APPROVED** [review]

**Comment by Slamdunk** [comment]
I'll push soon more commit before tagging a release: this was a quick copy-paste from our business code to show the solution to the problem; it needs some more code to be released, for example getting rid of public attributes.

Thanks for the contribution.

**Comment by Slamdunk** [comment]
I've tagged a stable release.

**Pull request merged**
